kind: pipeline
name: get-dependencies

workspace:
    base: /go
    path: src/github.com/saguywalker/add2git-lfs

steps:
- name: get
  image: golang
  commands:
    - go get ./...

- name: format
  image: golang
  commands:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

- name: test-func
  image: golang
  commands:
    - go test ./...

- name: compile
  image: golang
  commands:
    - go get github.com/GeertJohan/go.rice/rice
    - rice embed-go
    - CGO_ENABLED=0 go build

